name: Unit-Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tinydb
          python -m pip install pygame

      - name: Run Unit-Tests
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m unittest testdatabase
          python -m unittest testlogger
          python -m unittest testlogger2
          python -m unittest testmenu
          python -m unittest testskyfallgame
          python -m unittest testsnake
          python -m unittest testtetris